export const wordData = [
  {
    id: 1,
    word: "Car",
    czWord: "Auto",
    category: "Transportation",
  },
  {
    id: 2,
    word: "House",
    czWord: "Dům",
    category: "Buildings",
  },
  {
    id: 3,
    word: "Dog",
    czWord: "Pes",
    category: "Animals",
  },
  {
    id: 4,
    word: "Cat",
    czWord: "Kočka",
    category: "Animals",
  },
  {
    id: 5,
    word: "Book",
    czWord: "Kniha",
    category: "Education",
  },
  {
    id: 6,
    word: "Table",
    czWord: "Stůl",
    category: "Furniture",
  },
  {
    id: 7,
    word: "Computer",
    czWord: "Počítač",
    category: "Technology",
  },
  {
    id: 8,
    word: "Phone",
    czWord: "Telefon",
    category: "Technology",
  },
  {
    id: 9,
    word: "Chair",
    czWord: "Židle",
    category: "Furniture",
  },
  {
    id: 10,
    word: "Tree",
    czWord: "Strom",
    category: "Nature",
  },
  {
    id: 11,
    word: "Bicycle",
    czWord: "Kolo",
    category: "Transportation",
  },
  {
    id: 12,
    word: "Shoes",
    czWord: "Boty",
    category: "Clothing",
  },
  {
    id: 13,
    word: "Guitar",
    czWord: "Kytara",
    category: "Music",
  },
  {
    id: 14,
    word: "Water",
    czWord: "Voda",
    category: "Nature",
  },
  {
    id: 15,
    word: "Food",
    czWord: "Jídlo",
    category: "Cuisine",
  },
  {
    id: 16,
    word: "Friend",
    czWord: "Přítel",
    category: "People",
  },
  {
    id: 17,
    word: "Family",
    czWord: "Rodina",
    category: "People",
  },
  {
    id: 18,
    word: "City",
    czWord: "Město",
    category: "Places",
  },
  {
    id: 19,
    word: "Country",
    czWord: "Země",
    category: "Places",
  },
  {
    id: 20,
    word: "Music",
    czWord: "Hudba",
    category: "Entertainment",
  },
  {
    id: 21,
    word: "Movie",
    czWord: "Film",
    category: "Entertainment",
  },
];
