export const wordData = [
  {
    id: 1,
    word: "Car",
    czWord: "Auto",
    category: "Transportation",
  },
  {
    id: 2,
    word: "House",
    czWord: "Dům",
    category: "Buildings",
  },
  {
    id: 3,
    word: "Dog",
    czWord: "Pes",
    category: "Animals",
  },
  {
    id: 4,
    word: "Cat",
    czWord: "Kočka",
    category: "Animals",
  },
  {
    id: 5,
    word: "Bridge",
    czWord: "Most",
    category: "Buildings",
  },
  {
    id: 6,
    word: "Table",
    czWord: "Stůl",
    category: "Furniture",
  },
  {
    id: 7,
    word: "Computer",
    czWord: "Počítač",
    category: "Technology",
  },
  {
    id: 8,
    word: "Phone",
    czWord: "Telefon",
    category: "Technology",
  },
  {
    id: 9,
    word: "Shirt",
    czWord: "Košile",
    category: "Clothing",
  },
  {
    id: 10,
    word: "Tree",
    czWord: "Strom",
    category: "Nature",
  },
  {
    id: 11,
    word: "Bicycle",
    czWord: "Kolo",
    category: "Transportation",
  },
  {
    id: 12,
    word: "Shoes",
    czWord: "Boty",
    category: "Clothing",
  },
  {
    id: 13,
    word: "Guitar",
    czWord: "Kytara",
    category: "Music",
  },
  {
    id: 14,
    word: "Water",
    czWord: "Voda",
    category: "Nature",
  },
  {
    id: 15,
    word: "Elephant",
    czWord: "Slon",
    category: "Animals",
  },
  {
    id: 16,
    word: "Friend",
    czWord: "Přítel",
    category: "People",
  },
  {
    id: 17,
    word: "Family",
    czWord: "Rodina",
    category: "People",
  },
  {
    id: 18,
    word: "City",
    czWord: "Město",
    category: "Places",
  },
  {
    id: 19,
    word: "Country",
    czWord: "Země",
    category: "Places",
  },
  {
    id: 20,
    word: "Music",
    czWord: "Hudba",
    category: "Entertainment",
  },
  {
    id: 21,
    word: "Movie",
    czWord: "Film",
    category: "Entertainment",
  },
  {
    id: 22,
    word: "Sun",
    czWord: "Slunce",
    category: "Nature",
  },
  {
    id: 23,
    word: "Moon",
    czWord: "Měsíc",
    category: "Nature",
  },
  {
    id: 24,
    word: "Rain",
    czWord: "Déšť",
    category: "Weather",
  },
  {
    id: 25,
    word: "Fire",
    czWord: "Oheň",
    category: "Nature",
  },
  {
    id: 26,
    word: "Airplane",
    czWord: "Letadlo",
    category: "Transportation",
  },
  {
    id: 27,
    word: "Train",
    czWord: "Vlak",
    category: "Transportation",
  },
  {
    id: 28,
    word: "Beach",
    czWord: "Pláž",
    category: "Places",
  },
  {
    id: 29,
    word: "Mountain",
    czWord: "Hora",
    category: "Nature",
  },
  {
    id: 30,
    word: "Ocean",
    czWord: "Oceán",
    category: "Nature",
  },
  {
    id: 31,
    word: "Soccer",
    czWord: "Fotbal",
    category: "Sports",
  },
  {
    id: 32,
    word: "Basketball",
    czWord: "Basketbal",
    category: "Sports",
  },
  {
    id: 33,
    word: "Garden",
    czWord: "Zahrada",
    category: "Nature",
  },
  {
    id: 34,
    word: "Dress",
    czWord: "Šaty",
    category: "Clothing",
  },
  {
    id: 35,
    word: "Hat",
    czWord: "Klobouk",
    category: "Clothing",
  },
  {
    id: 36,
    word: "Dance",
    czWord: "Tanec",
    category: "Entertainment",
  },
  {
    id: 37,
    word: "Bird",
    czWord: "Pták",
    category: "Animals",
  },
  {
    id: 38,
    word: "Swimming",
    czWord: "Plavání",
    category: "Sports",
  },
  {
    id: 39,
    word: "Television",
    czWord: "Televize",
    category: "Technology",
  },
  {
    id: 40,
    word: "Fruit",
    czWord: "Ovoce",
    category: "Food",
  },
  {
    id: 41,
    word: "Vegetable",
    czWord: "Zelenina",
    category: "Food",
  },
  {
    id: 42,
    word: "Island",
    czWord: "Ostrov",
    category: "Places",
  },
  {
    id: 43,
    word: "Ice Cream",
    czWord: "Zmrzlina",
    category: "Food",
  },
  {
    id: 44,
    word: "Rainbow",
    czWord: "Duha",
    category: "Nature",
  },
  {
    id: 45,
    word: "Desert",
    czWord: "Poušť",
    category: "Nature",
  },
  {
    id: 46,
    word: "Carrot",
    czWord: "Mrkev",
    category: "Food",
  },
  {
    id: 47,
    word: "Concert",
    czWord: "Koncert",
    category: "Entertainment",
  },
  {
    id: 48,
    word: "Countryside",
    czWord: "Venkov",
    category: "Places",
  },
  {
    id: 49,
    word: "Bed",
    czWord: "Postel",
    category: "Furniture",
  },
  {
    id: 50,
    word: "Mirror",
    czWord: "Zrcadlo",
    category: "Furniture",
  },
  {
    id: 51,
    word: "Door",
    czWord: "Dveře",
    category: "Buildings",
  },
  {
    id: 52,
    word: "Window",
    czWord: "Okno",
    category: "Buildings",
  },
  {
    id: 53,
    word: "Laptop",
    czWord: "Notebook",
    category: "Technology",
  },
  {
    id: 54,
    word: "Cup",
    czWord: "Šálek",
    category: "Tableware",
  },
  {
    id: 55,
    word: "Plate",
    czWord: "Talíř",
    category: "Tableware",
  },
  {
    id: 56,
    word: "Spoon",
    czWord: "Lžíce",
    category: "Tableware",
  },
  {
    id: 57,
    word: "Fork",
    czWord: "Vidlička",
    category: "Tableware",
  },
  {
    id: 58,
    word: "Knife",
    czWord: "Nůž",
    category: "Tableware",
  },
  {
    id: 59,
    word: "Mountains",
    czWord: "Hory",
    category: "Nature",
  },
  {
    id: 60,
    word: "Valley",
    czWord: "Údolí",
    category: "Nature",
  },
  {
    id: 61,
    word: "Bedroom",
    czWord: "Ložnice",
    category: "Rooms",
  },
  {
    id: 62,
    word: "Living Room",
    czWord: "Obývací pokoj",
    category: "Rooms",
  },
  {
    id: 63,
    word: "Kitchen",
    czWord: "Kuchyně",
    category: "Rooms",
  },
  {
    id: 64,
    word: "Bathroom",
    czWord: "Koupelna",
    category: "Rooms",
  },
  {
    id: 65,
    word: "Keyboard",
    czWord: "Klávesnice",
    category: "Technology",
  },
  {
    id: 66,
    word: "Flower",
    czWord: "Květina",
    category: "Nature",
  },
  {
    id: 67,
    word: "Grass",
    czWord: "Tráva",
    category: "Nature",
  },
  {
    id: 68,
    word: "Sky",
    czWord: "Nebe",
    category: "Nature",
  },
  {
    id: 69,
    word: "Cloud",
    czWord: "Oblak",
    category: "Nature",
  },
  {
    id: 70,
    word: "Bus",
    czWord: "Autobus",
    category: "Transportation",
  },
  {
    id: 71,
    word: "Snow",
    czWord: "Sníh",
    category: "Weather",
  },
  {
    id: 72,
    word: "Clarinet",
    czWord: "Klarinet",
    category: "Music",
  },
  {
    id: 73,
    word: "Saxophone",
    czWord: "Saxofon",
    category: "Music",
  },
  {
    id: 74,
    word: "Toilet",
    czWord: "Záchod",
    category: "Rooms",
  },
  {
    id: 75,
    word: "Theater",
    czWord: "Divadlo",
    category: "Entertainment",
  },
  {
    id: 76,
    word: "Building",
    czWord: "Budova",
    category: "Buildings",
  },
  {
    id: 77,
    word: "Meadow",
    czWord: "Louka",
    category: "Nature",
  },
  {
    id: 78,
    word: "Coat",
    czWord: "Kabát",
    category: "Clothing",
  },
  {
    id: 79,
    word: "Screen",
    czWord: "Obrazovka",
    category: "Technology",
  },
  {
    id: 80,
    word: "Girl",
    czWord: "Holka",
    category: "People",
  },
  {
    id: 81,
    word: "Bananas",
    czWord: "Banány",
    category: "Food",
  },
  {
    id: 82,
    word: "Snake",
    czWord: "Had",
    category: "Animals",
  },
  {
    id: 83,
    word: "Sister",
    czWord: "Sestra",
    category: "People",
  },
  {
    id: 84,
    word: "Sweater",
    czWord: "Svetr",
    category: "Clothing",
  },
  {
    id: 85,
    word: "Lake",
    czWord: "Jezero",
    category: "Nature",
  },
  {
    id: 86,
    word: "River",
    czWord: "Řeka",
    category: "Nature",
  },
  {
    id: 87,
    word: "Forest",
    czWord: "Les",
    category: "Nature",
  },
  {
    id: 88,
    word: "Hockey",
    czWord: "Hokej",
    category: "Sports",
  },
  {
    id: 89,
    word: "Hamster",
    czWord: "Křeček",
    category: "Animals",
  },
  {
    id: 90,
    word: "Keyboard",
    czWord: "Klávesy",
    category: "Music",
  },
  {
    id: 91,
    word: "Horse",
    czWord: "Kůň",
    category: "Animals",
  },
  {
    id: 92,
    word: "Flute",
    czWord: "Flétna",
    category: "Music",
  },
  {
    id: 93,
    word: "Drizzle",
    czWord: "Mrholení",
    category: "Weather",
  },
  {
    id: 94,
    word: "Storm",
    czWord: "Bouře",
    category: "Weather",
  },
  {
    id: 95,
    word: "Basketball",
    czWord: "Basketbal",
    category: "Sports",
  },
  {
    id: 96,
    word: "Wind",
    czWord: "Vítr",
    category: "Weather",
  },
  {
    id: 97,
    word: "Tennis",
    czWord: "Tenis",
    category: "Sports",
  },
  {
    id: 98,
    word: "Flood",
    czWord: "Záplava",
    category: "Weather",
  },
  {
    id: 99,
    word: "Parrot",
    czWord: "Papoušek",
    category: "Animals",
  },
  {
    id: 100,
    word: "Violin",
    czWord: "Housle",
    category: "Music",
  },
  {
    id: 101,
    word: "Ice skating",
    czWord: "Bruslení",
    category: "Sports",
  },
  {
    id: 102,
    word: "Rabbit",
    czWord: "Králík",
    category: "Animals",
  },
  {
    id: 103,
    word: "Potatoes",
    czWord: "Brambory",
    category: "Food",
  },
  {
    id: 104,
    word: "Brother",
    czWord: "Bratr",
    category: "People",
  },
];
